name: jenkins
instance_groups:
- name: jenkins-master
  azs: [z1]
  instances: 1
  jobs:
  - name: jenkins-master
    release: jenkins-boshrelease
    properties:
      jenkins:
        config: config.xml
        admin:
          email: admin@localhost
          password: ((jenkins_admin_password))
        agent:
          password: ((jenkins_agent_password))
        server:
          address: ((jenkins_server_url))
  networks:
  - name: default
  stemcell: default
  vm_type: default
- name: jenkins-slave
  azs: [z1]
  instances: 1
  jobs:
  - name: jenkins-slave
    release: jenkins-boshrelease
    properties:
      jenkins:
        slave:
          executors: 2
          labels: build
          master_password: ((jenkins_agent_password))
          master_username: agent
          mode: exclusive
  networks:
  - name: default
  stemcell: default
  vm_type: default

releases:
- name: jenkins-boshrelease
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 15000-300000
  max_in_flight: 1
  update_watch_time: 15000-300000

variables:
- name: jenkins_admin_password
  type: password
- name: jenkins_agent_password
  type: password
