platform: linux
image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
inputs:
- name: devtools-boshrelease
- name: version
outputs:
- name: final-release-tarball
run:
  path: bash
  args:
  - -c
  - | 
    version=$(<version/version)
    bosh create-release \
      --tarball=final-release-tarball/devtools-boshrelease-v$version.tgz \
      --dir=devtools-boshrelease \
      --final \
      --version="$version"
