platform: linux
image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
inputs:
- name: devtools-boshrelease
outputs:
- name: dev-release-tarball
run:
  path: bash
  args:
  - -c
  - | 
    bosh create-release \
      --tarball=dev-release-tarball/dev-release.tgz \
      --dir=devtools-boshrelease \
      --timestamp-version
