platform: linux
image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
inputs:
- name: jenkins-boshrelease
- name: version
outputs:
- name: final-jenkins-boshrelease-tarball
run:
  path: bash
  args:
  - -c
  - | 
    version=$(<version/version)
    bosh create-release \
      --tarball=final-jenkins-boshrelease-tarball/jenkins-boshrelease-v$version.tgz \
      --dir=jenkins-boshrelease \
      --final \
      --version="$version"
