platform: linux
image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
inputs:
- name: bbl-state
outputs:
- name: source
run:
  path: bash
  args:
  - -c
  - |
    set -euo pipefail
    eval "$(cd bbl-state/bbl-state; bbl print-env)"
    jq -n \
    --arg "deployment" "$BOSH_DEPLOYMENT" \
    --arg "target" "$BOSH_ENVIRONMENT" \
    --arg "client" "$BOSH_CLIENT" \
    --arg "client_secret" "$BOSH_CLIENT_SECRET" \
    --arg "ca_cert" "$BOSH_CA_CERT" \
    --arg "jumpbox_url" "$(sed 's/.*@\(.*\):.*/\1:22/' <<< "$BOSH_ALL_PROXY")" \
    --arg "jumpbox_ssh_key" "$(<$JUMPBOX_PRIVATE_KEY)" \
    --arg "jumpbox_username" "jumpbox" \
    '{
        "deployment": $deployment,
        "target": $target,
        "client": $client,
        "client_secret": $client_secret,
        "ca_cert": $ca_cert,
        "jumpbox_url": $jumpbox_url,
        "jumpbox_ssh_key": $jumpbox_ssh_key,
        "jumpbox_username": $jumpbox_username
    }' > source/source.yml