platform: linux
image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
inputs:
- name: bbl-state
- name: jenkins-boshrelease
- name: devtools-tests
run:
  path: /bin/bash
  args:
  - -c
  - | 
    pushd bbl-state/bbl-state
      source <(bbl print-env)
      if [[ $BOSH_LITE == true ]]; then
        JUMPBOX_USER="jumpbox"; export JUMPBOX_USER
        JUMPBOX_HOST=$(bosh int <(bbl outputs) --path /jumpbox_url | cut -d: -f1); export JUMPBOX_HOST
        # set up jumpbox ssh tunnel
        instance_info=$(bosh --json instances -i); export instance_info
        ip=$(jq --raw-output .Tables[0].Rows[0].ips <<< "$instance_info")
        # shellcheck disable=SC2029
        ssh -o StrictHostKeyChecking=no -fNnL "8080:$ip:8080" -i "$JUMPBOX_PRIVATE_KEY" "$JUMPBOX_USER@$JUMPBOX_HOST"
        trap "pkill ssh" EXIT
      fi
      export JENKINS_PASSWORD=$(credhub get --name=${JENKINS_PASSWORD_CREDHUB_PATH} --output-json | jq --raw-output ".value" | tr --delete ' ')
    popd

    export INSTALLED_PLUGINS_FILE_PATH="${PWD}/${INSTALLED_PLUGINS_FILE_PATH_SUFFIX}"
    cp -R devtools-tests/* /go/src/
    sleep 10

    pushd /go/src
      go get github.com/DATA-DOG/godog/cmd/godog
      set -e
      godog $TEST_TAGS features/**/*.feature # See godog --help, to understand how to apply tags.
    popd
