azs:
- name: z1
  cloud_properties:
    zone: europe-west2-a
- name: z2
  cloud_properties:
    zone: europe-west2-b
- name: z3
  cloud_properties:
    zone: europe-west2-c

vm_types:
- name: default
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
- name: compile
  cloud_properties:
    machine_type: n1-highcpu-4
    root_disk_size_gb: 20
    root_disk_type: pd-ssd

networks:
- name: default
  type: manual
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    azs: [z1, z2, z3]
    dns: [8.8.8.8, 8,8.4.4]
    cloud_properties:
      network_name: ((network))
      subnetwork_name: ((subnetwork))
      ephemeral_external_ip: false
      tags: [internal, no-ip]
      preemptible: true

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: compile
  network: default
  vm_extensions:
  - 50GB_ephemeral_disk

vm_extensions:
  - cloud_properties:
    root_disk_size_gb: 50
    root_disk_type: pd-ssd
  name: 50GB_ephemeral_disk