platform: linux
image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
inputs:
- name: devtools-boshrelease 
run:
  path: /bin/bash
  args:
  - -c
  - | 
    cp -R devtools-boshrelease/ci/tasks/publish-draft-release /go/src/
    cd /go/src/publish-draft-release
    go run publish-draft-release.go ${OWNER} ${REPO} ${VERSION} ${BRANCH}
